### ISSUE TITLE
See also link to "UI contrast and settings sample" doesn't work

### ISSUE THREAD

**Issue by dotMorten** [MicrosoftDocs/winrt-api#1431]
No sample is listed, nor can I find it when I search for it on the linked page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e2dadb1-6e38-139d-4346-641b40a509d7
* Version Independent ID: d93daf2b-471d-fc73-b2b8-af92ebc1e38c
* Content: [UISettings Class (Windows.UI.ViewManagement) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.viewmanagement.uisettings#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.viewmanagement.uisettings.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.viewmanagement.uisettings.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks @dotMorten. The link should be fixed now.

**Comment by dotMorten** [comment]
@Karl-Bridge-Microsoft I'm still seeing it link to an outdated sample site, that doesn't contain that sample

**Comment by Karl-Bridge-Microsoft** [comment]
We had a block in our build pipeline. Valid link now.
