### ISSUE TITLE
Unable to open files

### ISSUE THREAD

**Issue by gallantrinity** [MicrosoftDocs/winrt-api#845]
The default save and open directory for apps is Documents folder. File explorer returns error when trying to open or save documents. Should be able to view Downloads, external drives and network drives when opening files from apps. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a38d03d-7e03-daf4-ede9-b557fe0aed71
* Version Independent ID: da626426-209d-1118-01a9-5d899fcc2b75
* Content: [SharedModeSettings.ShouldAvoidLocalStorage Property (Windows.System.Profile) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.system.profile.sharedmodesettings.shouldavoidlocalstorage#Windows_System_Profile_SharedModeSettings_ShouldAvoidLocalStorage)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.system.profile.sharedmodesettings.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.system.profile.sharedmodesettings.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **hickeys**
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
I've passed this feedback along to the developer. There was a bug related to this that was fixed in the Windows 10 April 2018 Update, so please be sure you've updated. If you are seeing the behavior on updated versions of Windows 10, please let me know and I will have the developer open a bug.

**Comment by gallan13** [comment]
Thanks for the quick response! Our devices are on Windows 10 1803 and unfortunately are still experiencing this behavior. Let me know if we need to do anything specific for troubleshooting solutions.

**Comment by hickeys** [comment]
Not at the moment, but I'll contact you privately if we have additional questions. I'm going to open a bug for the devs and close this GitHub Issue. 

Thanks for bringing this to our attention,
Shawn

**Comment by gallan13** [comment]
What's the status on this?

**Comment by hickeys** [comment]
The devs would like some more information about your repro steps, can you reach out to me at [my github username]@microsoft.com? It would be easier to continue this over email than to use github comments :)

**Comment by gallantrinity** [comment]
Shawn,

Let me know what ever you need to proceed with resolving this issue.

Thanks,

George Allan
Systems Administrator

TRINITY PROPERTY CONSULTANTS
2082 Michelson Drive, 4th Floor
Irvine, CA 92612

T 949.299.0815 | F 949.399.2530
GAllan@trinity-pm.com<mailto:GAllan@trinity-pm.com>  | www.FPAMF.com<http://www.fpamf.com/> |  www.trinity-pm.com<http://www.trinity-pm.com/>
Click to open a Helpdesk<https://trinitypm.zendesk.com/> Ticket

[cid:image001.jpg@01D41EA5.E54FDB00]<http://www.fpamf.com/>     [cid:image002.png@01D41EA5.E54FDB00] <http://www.trinity-pm.com/>

ATLANTA   -   DALLAS   -   DENVER   -   IRVINE   -   MINNEAPOLIS   -   PORTLAND   -   SAN FRANCISCO

[Description: Description: cid:image001.gif@01C948B1.CFC0CC60] Please consider the environment before printing this e-mail [Description: Description: cid:image001.gif@01C948B1.CFC0CC60]
